export const Icons = {
  // logOutIcon: require('./log_out_icon.png'),
  // noWifi: require('./nowifi.png'),
  // noInternate: require('./no_Internate.png'),

  passwordicon: require('./password_icon.png'),
  callIcon: require('./call_icon.png'),
  homeIcon: require('./Frame.png'),
  drawerIcon: require('./drawer_icon.png'),
  notificationIcon: require('./notification.png'),
  questionMarkIcon: require('./question_mark_icon.png'),
  logOutIcon: require('./log_out_icon.png'),
  // serchIcon: require('./serch_icon.png'),

  // footer icon
  specialityIcon: require('./speciality_icon.png'),
  supportIcon: require('./support_icon.png'),
  userProfileIcon: require('./user_profile_icon.png'),
  leftIcon: require('./left_icon.png'),
  cancleIcon: require('./cancle_Icon.png'),
  footerNotificationIcon: require('./footer_notification_icon.png'),

  //doctor list
  verificationIcon: require('./verification_icon.png'),
  rightVerticalArrow: require('./right_vertical_arrow.png'),
  callFillIcon: require('./call_fill_icon.png'),
  emailIcon: require('./email_icon.png'),
  emailOutlineIcon: require('./email_outline_icon.png'),
  dateIcon: require('./date_icon.png'),
  namecon: require('./name_icon.png'),
  mapFillIcon: require('./map_fill_icon.png'),
  mapIcon: require('./map_icon.png'),
  checkIcon: require('./check.png'),
  clockIcon: require('./clock.png'),
  addIcon: require('./add_icon.png'),
  addIconReport: require('./add_icon_report.png'),
  hospitalIcon: require('./hospital_icon.png'),
  calendarIcon: require('./calendar_icon.png'),
  branchIcon: require('./branch_icon.png'),
  marritalStatusIcon: require('./marrital_status_icon.png'),
  healthcareIcon: require('./healthcare_icon.png'),
  doctorListIcon: require('./doctor_list_icon.png'),
  privacyPolicyIcon: require('./privacy_policy_icon.png'),
  termAndConditionIcon: require('./term_And_condition_icon.png'),
  appointment_icon: require('./appointment_icon.png'),
  nephrologyIcon: require('./nephrology_icon.png'),
  reportIcon: require('./report_icon.png'),
  reportTabIcon: require('./report_tab_icon.png'),
};
