export const ApiEndPoint = {
  LoGIN: 'login-otp',
  LoGINROlE: 'login',
  Question: 'question',
  Board: 'boards',
  Medium: 'medium',
  Classes: 'classes',
  Banner: 'banner',
  Subject: 'subject',
  UpdateProfile: 'update-profile',
  GetProfile: 'get-profile',
  bookFetch: 'book',
  questionChapter: 'question-chapter',
  difficultyLabel: 'difficulty-level',
  questiontype: 'queation-type',
  questionDetail: 'question-detail',
  updateRole: 'update-role',
  draftAdd: 'draft-add',
  draftList: 'draft-list',
  draftDelete: 'draft-delete',
  questionReport: 'question-report',
  questionReportList: 'question-report-list',
  // DeleteAccount :'deleteAccount',
  privacyPolicy: 'privacy-policy',
  aboutUs: 'about-us',
  termCondition: 'term-condition',
  latestNews: 'latest-news',
  deleteAccount: 'delete-account',
  support: 'support',
  question: 'question',
  questionBucket: 'question-bucket',
  ticketFaq: 'ticket-faq',

  // PDF Module
  paperGenerate: 'paper-generate',
  paperList: 'paper-list',
  paperDelete: 'paper-delete',
};
