export const ApiEndPoint = {
  LoGIN: 'login',
  listSpeciality: 'list-speciality',
  medicineBySpecilityId: 'get-medicine-by-speciality-id',
  getProfile: 'get-profile',
  updateProfile: 'update-profile',
  stateList: 'state-list',
  cityList: 'city-list',
  dailyVisit: 'list-daily-visit-by-member-id',
  listDoctor: 'list-doctor',
  addDoctor: 'add-doctor',
  updateDoctor: 'update-doctor',
  detailsDoctor: 'details-doctor',
  addDailyVisitByMemberId: 'add-daily-visit-by-member-id',
  doctorMedicine: 'doctor-medicine',
  addAppointment: 'add-appointment',
  listAppointment: 'list-appointment',
  detailsAppointment: 'details-appointment',
  banner: 'banner',
  support: 'support',
  supportMail: 'support-mail',
  notificationList: 'notification-list',
};
