export const ApiEndPoint = {
  LoGIN: 'login',
  listSpeciality: 'list-speciality',
  medicineBySpecilityId: 'get-medicine-by-speciality-id',
  getProfile: 'get-profile',
  stateList: 'state-list',
  cityList: 'city-list',
  dailyVisit: 'list-daily-visit-by-member-id',
  listDoctor: 'list-doctor',
  addDoctor: 'add-doctor',
  updateDoctor: 'update-doctor',
  detailsDoctor: 'details-doctor',
  addDailyVisitByMemberId: 'add-daily-visit-by-member-id',
  doctorMedicine: 'doctor-medicine',
};
